/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Temporadas con sus campeones */
        get: operations["list_seasons_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendario de una temporada */
        get: operations["get_season_seasons__season__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{season}/standings/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clasificación de pilotos (tras la última carrera o la ronda indicada) */
        get: operations["driver_standings_seasons__season__standings_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{season}/standings/constructors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clasificación de constructores (desde 1958) */
        get: operations["constructor_standings_seasons__season__standings_constructors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{season}/standings/progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Puntos acumulados ronda a ronda (gráfico de evolución del campeonato) */
        get: operations["standings_progression_seasons__season__standings_progression_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/races/{race_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datos de la carrera y el circuito */
        get: operations["get_race_races__race_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/races/{race_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resultado */
        get: operations["race_results_races__race_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/races/{race_id}/qualifying": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clasificación */
        get: operations["qualifying_races__race_id__qualifying_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/races/{race_id}/laps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vuelta a vuelta: posición, tiempos, neumático y estado de pista */
        get: operations["laps_races__race_id__laps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/races/{race_id}/stints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estrategia de neumáticos: tramos entre paradas con su compuesto */
        get: operations["stints_races__race_id__stints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/races/{race_id}/pitstops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paradas en boxes */
        get: operations["pit_stops_races__race_id__pitstops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/races/{race_id}/pit-lane-passes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Todas las entradas al pit lane, tipificadas (paradas, Safety Car, sanciones...) */
        get: operations["pit_lane_passes_races__race_id__pit_lane_passes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/races/{race_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telemetría de la vuelta más rápida de clasificación (2024+) */
        get: operations["telemetry_races__race_id__telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar pilotos */
        get: operations["list_drivers_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{driver_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ficha y estadísticas de carrera */
        get: operations["get_driver_drivers__driver_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{driver_id}/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Temporada a temporada */
        get: operations["driver_seasons_drivers__driver_id__seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{driver_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resultados carrera a carrera */
        get: operations["driver_results_drivers__driver_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{driver_id}/teammates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comparativa con cada compañero de equipo (carrera, clasificación y puntos) */
        get: operations["teammates_drivers__driver_id__teammates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constructors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar constructores */
        get: operations["list_constructors_constructors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constructors/{constructor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ficha del constructor */
        get: operations["get_constructor_constructors__constructor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constructors/{constructor_id}/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Temporada a temporada: posición en el campeonato, victorias y pilotos */
        get: operations["constructor_seasons_constructors__constructor_id__seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranking histórico de pilotos */
        get: operations["driver_records_records_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/constructors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranking histórico de constructores */
        get: operations["constructor_records_records_constructors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rankings/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pilotos más laureados */
        get: operations["driver_rankings_rankings_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rankings/constructors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Constructores más laureados */
        get: operations["constructor_rankings_rankings_constructors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/circuits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Circuitos y carreras disputadas en cada uno */
        get: operations["list_circuits_circuits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado y versión de los datos */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Controles de calidad de los datos (concordancia entre fuentes) */
        get: operations["quality_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Circuit */
        Circuit: {
            /** Circuit Id */
            circuit_id: string;
            /** Name */
            name: string;
            /** Place */
            place: string | null;
            /** Country */
            country: string;
            /** Country Alpha2 */
            country_alpha2: string | null;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /** Races */
            races: number;
            /** First Season */
            first_season: number;
            /** Last Season */
            last_season: number;
            /** Grands Prix */
            grands_prix: string[];
        };
        /** ConstructorDetail */
        ConstructorDetail: {
            /** Constructor Id */
            constructor_id: string;
            /** Name */
            name: string;
            /** Country Alpha2 */
            country_alpha2: string | null;
            /** First Season */
            first_season: number | null;
            /** Last Season */
            last_season: number | null;
            /** Race Entries */
            race_entries: number;
            /** Wins */
            wins: number;
            /** Championships */
            championships: number;
            /** Full Name */
            full_name: string | null;
            /** Country */
            country: string | null;
            /** Podiums */
            podiums: number;
            /** One Two Finishes */
            one_two_finishes: number;
            /** Pole Positions */
            pole_positions: number;
            /** Fastest Laps */
            fastest_laps: number;
            /** Race Points */
            race_points: number;
            /** Best Championship Position */
            best_championship_position: number | null;
        };
        /** ConstructorRanking */
        ConstructorRanking: {
            /** Rank */
            rank: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Country */
            country: string | null;
            /** Country Alpha2 */
            country_alpha2: string | null;
            /** Entries */
            entries: number;
            /** Wins */
            wins: number;
            /** Podiums */
            podiums: number;
            /** Pole Positions */
            pole_positions: number;
            /** Fastest Laps */
            fastest_laps: number;
            /** Points */
            points: number;
            /** Championships */
            championships: number;
        };
        /** ConstructorSeason */
        ConstructorSeason: {
            /** Season */
            season: number;
            /** Championship Position */
            championship_position: number | null;
            /** Championship Position Text */
            championship_position_text: string | null;
            /** Points */
            points: number | null;
            /** Is Champion */
            is_champion: boolean;
            /** Wins */
            wins: number;
            /** Drivers */
            drivers: components["schemas"]["Ref"][];
        };
        /** ConstructorStanding */
        ConstructorStanding: {
            /** Position */
            position: number | null;
            /** Position Text */
            position_text: string;
            /** Constructor Id */
            constructor_id: string;
            /** Name */
            name: string;
            /** Country Alpha2 */
            country_alpha2: string | null;
            /** Engine */
            engine: string | null;
            /** Points */
            points: number;
            /** Wins */
            wins: number;
            /** Is Champion */
            is_champion: boolean;
        };
        /** ConstructorSummary */
        ConstructorSummary: {
            /** Constructor Id */
            constructor_id: string;
            /** Name */
            name: string;
            /** Country Alpha2 */
            country_alpha2: string | null;
            /** First Season */
            first_season: number | null;
            /** Last Season */
            last_season: number | null;
            /** Race Entries */
            race_entries: number;
            /** Wins */
            wins: number;
            /** Championships */
            championships: number;
        };
        /** DataInfo */
        DataInfo: {
            /**
             * Version
             * @description Cambia con cada publicación de datos (se usa en las ETag)
             */
            version: string;
            /** Generated At */
            generated_at: string | null;
            /** F1Db Release */
            f1db_release: string | null;
            last_completed_race: components["schemas"]["RaceRef"] | null;
        };
        /** DriverDetail */
        DriverDetail: {
            /** Driver Id */
            driver_id: string;
            /** Name */
            name: string;
            /** Nationality Alpha2 */
            nationality_alpha2: string | null;
            /** First Season */
            first_season: number | null;
            /** Last Season */
            last_season: number | null;
            /** Race Starts */
            race_starts: number;
            /** Wins */
            wins: number;
            /** Podiums */
            podiums: number;
            /** Championships */
            championships: number;
            /** Full Name */
            full_name: string | null;
            /** Abbreviation */
            abbreviation: string | null;
            /** Permanent Number */
            permanent_number: string | null;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Date Of Death */
            date_of_death: string | null;
            /** Place Of Birth */
            place_of_birth: string | null;
            /** Nationality */
            nationality: string | null;
            /** Race Entries */
            race_entries: number;
            /** Pole Positions */
            pole_positions: number;
            /** Fastest Laps */
            fastest_laps: number;
            /** Grand Slams */
            grand_slams: number;
            /** Points */
            points: number;
            /** Best Race Result */
            best_race_result: number | null;
            /** Best Championship Position */
            best_championship_position: number | null;
            /** Laps Completed */
            laps_completed: number | null;
            /** Win Rate Pct */
            win_rate_pct: number | null;
            /** Podium Rate Pct */
            podium_rate_pct: number | null;
        };
        /** DriverRaceResult */
        DriverRaceResult: {
            /** Race Id */
            race_id: number;
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Grand Prix Name */
            grand_prix_name: string;
            /** Session */
            session: string;
            /** Constructor Id */
            constructor_id: string;
            /** Position */
            position: number | null;
            /** Position Text */
            position_text: string;
            /** Grid Position */
            grid_position: number | null;
            /** Points */
            points: number;
        };
        /** DriverRanking */
        DriverRanking: {
            /** Rank */
            rank: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Country */
            country: string | null;
            /** Country Alpha2 */
            country_alpha2: string | null;
            /** Entries */
            entries: number;
            /** Wins */
            wins: number;
            /** Podiums */
            podiums: number;
            /** Pole Positions */
            pole_positions: number;
            /** Fastest Laps */
            fastest_laps: number;
            /** Points */
            points: number;
            /** Championships */
            championships: number;
            /** Starts */
            starts: number;
        };
        /** DriverSeason */
        DriverSeason: {
            /** Season */
            season: number;
            /** Constructor Id */
            constructor_id: string | null;
            /** Constructor Name */
            constructor_name: string | null;
            /** Championship Position */
            championship_position: number | null;
            /** Championship Position Text */
            championship_position_text: string | null;
            /** Points */
            points: number | null;
            /** Is Champion */
            is_champion: boolean;
            /** Races */
            races: number;
            /** Wins */
            wins: number;
            /** Podiums */
            podiums: number;
            /** Pole Positions */
            pole_positions: number;
            /** Fastest Laps */
            fastest_laps: number;
            /** Best Result */
            best_result: number | null;
        };
        /** DriverStanding */
        DriverStanding: {
            /** Position */
            position: number | null;
            /** Position Text */
            position_text: string;
            /** Driver Id */
            driver_id: string;
            /** Name */
            name: string;
            /** Nationality Alpha2 */
            nationality_alpha2: string | null;
            /** Constructors */
            constructors: string[];
            /** Points */
            points: number;
            /** Wins */
            wins: number;
            /** Is Champion */
            is_champion: boolean;
        };
        /** DriverSummary */
        DriverSummary: {
            /** Driver Id */
            driver_id: string;
            /** Name */
            name: string;
            /** Nationality Alpha2 */
            nationality_alpha2: string | null;
            /** First Season */
            first_season: number | null;
            /** Last Season */
            last_season: number | null;
            /** Race Starts */
            race_starts: number;
            /** Wins */
            wins: number;
            /** Podiums */
            podiums: number;
            /** Championships */
            championships: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            data: components["schemas"]["DataInfo"];
        };
        /** Lap */
        Lap: {
            /** Driver Id */
            driver_id: string;
            /** Lap */
            lap: number;
            /** Position */
            position: number | null;
            /** Lap Time Ms */
            lap_time_ms: number | null;
            /** Gap To Leader Ms */
            gap_to_leader_ms: number | null;
            /** Sector 1 Ms */
            sector_1_ms: number | null;
            /** Sector 2 Ms */
            sector_2_ms: number | null;
            /** Sector 3 Ms */
            sector_3_ms: number | null;
            /**
             * Compound
             * @description Compuesto relativo si se conoce; si no, el publicado
             */
            compound: string | null;
            /** Compound Pirelli */
            compound_pirelli: string | null;
            /** Tyre Age Laps */
            tyre_age_laps: number | null;
            /** Is Pit In Lap */
            is_pit_in_lap: boolean | null;
            /** Is Pit Out Lap */
            is_pit_out_lap: boolean | null;
            /** Is Yellow Flag */
            is_yellow_flag: boolean | null;
            /** Is Safety Car */
            is_safety_car: boolean | null;
            /** Is Virtual Safety Car */
            is_virtual_safety_car: boolean | null;
            /** Is Red Flag */
            is_red_flag: boolean | null;
            /** Source */
            source: string;
            /** Validation Status */
            validation_status: string;
        };
        /** PitLanePass */
        PitLanePass: {
            /** Driver Id */
            driver_id: string;
            /** Lap */
            lap: number;
            /**
             * Pass Type
             * @description pit_stop, safety_car, red_flag, retirement, penalty_or_other o unclassified
             */
            pass_type: string;
            /** Stop */
            stop: number | null;
        };
        /** PitStop */
        PitStop: {
            /** Driver Id */
            driver_id: string;
            /** Driver Name */
            driver_name: string;
            /** Constructor Id */
            constructor_id: string | null;
            /** Stop */
            stop: number;
            /** Lap */
            lap: number;
            /** Duration Ms */
            duration_ms: number | null;
        };
        /** QualifyingResult */
        QualifyingResult: {
            /** Position */
            position: number | null;
            /** Position Text */
            position_text: string;
            /** Driver Number */
            driver_number: string | null;
            /** Driver Id */
            driver_id: string;
            /** Driver Name */
            driver_name: string;
            /** Constructor Id */
            constructor_id: string;
            /** Constructor Name */
            constructor_name: string;
            /** Q1 Ms */
            q1_ms: number | null;
            /** Q2 Ms */
            q2_ms: number | null;
            /** Q3 Ms */
            q3_ms: number | null;
            /** Best Time Ms */
            best_time_ms: number | null;
            /** Gap To Pole Pct */
            gap_to_pole_pct: number | null;
        };
        /** QualityCheck */
        QualityCheck: {
            /** Check Id */
            check_id: string;
            /** Description */
            description: string;
            /** Compared */
            compared: number;
            /** Matched */
            matched: number;
            /** Match Pct */
            match_pct: number | null;
            /** Min Match Pct */
            min_match_pct: number | null;
            /**
             * Status
             * @description PASS, FAIL, INFO o NO_DATA
             */
            status: string;
        };
        /** RaceDetail */
        RaceDetail: {
            /** Race Id */
            race_id: number;
            /** Season */
            season: number;
            /** Round */
            round: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Grand Prix Id */
            grand_prix_id: string;
            /** Grand Prix Name */
            grand_prix_name: string;
            /** Official Name */
            official_name: string;
            /** Circuit Id */
            circuit_id: string;
            /** Circuit Name */
            circuit_name: string;
            /** Country */
            country: string;
            /** Country Alpha2 */
            country_alpha2: string | null;
            /** Has Sprint */
            has_sprint: boolean;
            /** Is Completed */
            is_completed: boolean;
            winner: components["schemas"]["Ref"] | null;
            /** Race Time Utc */
            race_time_utc: string | null;
            /** Laps */
            laps: number | null;
            /** Distance Km */
            distance_km: number | null;
            /** Circuit Type */
            circuit_type: string | null;
            /** Direction */
            direction: string | null;
            /** Course Length Km */
            course_length_km: number | null;
            /** Turns */
            turns: number | null;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /** Is Season Final Race */
            is_season_final_race: boolean;
        };
        /** RaceRef */
        RaceRef: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Name */
            name: string;
        };
        /** RaceResult */
        RaceResult: {
            /** Position */
            position: number | null;
            /** Position Text */
            position_text: string;
            /** Driver Number */
            driver_number: string | null;
            /** Driver Id */
            driver_id: string;
            /** Driver Name */
            driver_name: string;
            /** Constructor Id */
            constructor_id: string;
            /** Constructor Name */
            constructor_name: string;
            /** Grid Position */
            grid_position: number | null;
            /** Grid Position Text */
            grid_position_text: string | null;
            /** Laps */
            laps: number | null;
            /** Time Ms */
            time_ms: number | null;
            /** Gap Ms */
            gap_ms: number | null;
            /** Gap Laps */
            gap_laps: number | null;
            /** Points */
            points: number;
            /** Positions Gained */
            positions_gained: number | null;
            /** Pit Stops */
            pit_stops: number | null;
            /** Reason Retired */
            reason_retired: string | null;
            /** Is Fastest Lap */
            is_fastest_lap: boolean;
            /**
             * Corrected Fields
             * @description Campos corregidos respecto a F1DB con evidencia documentada
             */
            corrected_fields: string[];
        };
        /** RaceSummary */
        RaceSummary: {
            /** Race Id */
            race_id: number;
            /** Season */
            season: number;
            /** Round */
            round: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Grand Prix Id */
            grand_prix_id: string;
            /** Grand Prix Name */
            grand_prix_name: string;
            /** Official Name */
            official_name: string;
            /** Circuit Id */
            circuit_id: string;
            /** Circuit Name */
            circuit_name: string;
            /** Country */
            country: string;
            /** Country Alpha2 */
            country_alpha2: string | null;
            /** Has Sprint */
            has_sprint: boolean;
            /** Is Completed */
            is_completed: boolean;
            winner: components["schemas"]["Ref"] | null;
        };
        /** RecordEntry */
        RecordEntry: {
            /** Rank */
            rank: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Country Alpha2 */
            country_alpha2: string | null;
            /** Value */
            value: number;
        };
        /** Ref */
        Ref: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** SeasonDetail */
        SeasonDetail: {
            /** Season */
            season: number;
            /** Races */
            races: components["schemas"]["RaceSummary"][];
        };
        /** SeasonSummary */
        SeasonSummary: {
            /** Season */
            season: number;
            /** Races */
            races: number;
            /** Completed Races */
            completed_races: number;
            drivers_champion: components["schemas"]["Ref"] | null;
            constructors_champion: components["schemas"]["Ref"] | null;
        };
        /** StandingsProgression */
        StandingsProgression: {
            /** Round */
            round: number;
            /** Race Id */
            race_id: number;
            /** Grand Prix Name */
            grand_prix_name: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Points */
            points: number;
            /** Position */
            position: number | null;
        };
        /** Stint */
        Stint: {
            /** Driver Id */
            driver_id: string;
            /** Stint */
            stint: number;
            /** Compound */
            compound: string | null;
            /** Start Lap */
            start_lap: number;
            /** End Lap */
            end_lap: number;
            /** Laps */
            laps: number;
            /** Tyre Age At Start */
            tyre_age_at_start: number | null;
        };
        /** TeammateComparison */
        TeammateComparison: {
            /** Season */
            season: number;
            /** Constructor Id */
            constructor_id: string;
            /** Constructor Name */
            constructor_name: string;
            /** Teammate Id */
            teammate_id: string;
            /** Teammate Name */
            teammate_name: string;
            /** Races Together */
            races_together: number;
            /** Race Ahead */
            race_ahead: number;
            /** Race Ahead Pct */
            race_ahead_pct: number | null;
            /** Qualifyings Together */
            qualifyings_together: number;
            /** Quali Ahead */
            quali_ahead: number;
            /** Quali Ahead Pct */
            quali_ahead_pct: number | null;
            /** Points */
            points: number | null;
            /** Teammate Points */
            teammate_points: number | null;
        };
        /**
         * TelemetryLap
         * @description Vuelta más rápida de clasificación, muestreada cada 10 m (listas paralelas).
         */
        TelemetryLap: {
            /** Driver Id */
            driver_id: string;
            /** Driver Code */
            driver_code: string | null;
            /** Lap Time Ms */
            lap_time_ms: number | null;
            /** Tyre Compound */
            tyre_compound: string | null;
            /** Distance M */
            distance_m: number[];
            /** Speed Kmh */
            speed_kmh: (number | null)[];
            /** Throttle Pct */
            throttle_pct: (number | null)[];
            /** Is Braking */
            is_braking: (boolean | null)[];
            /** Gear */
            gear: (number | null)[];
            /** X */
            x: (number | null)[];
            /** Y */
            y: (number | null)[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_seasons_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonSummary"][];
                };
            };
        };
    };
    get_season_seasons__season__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_standings_seasons__season__standings_drivers_get: {
        parameters: {
            query?: {
                /** @description Tras esta ronda */
                round?: number | null;
            };
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverStanding"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    constructor_standings_seasons__season__standings_constructors_get: {
        parameters: {
            query?: {
                /** @description Tras esta ronda */
                round?: number | null;
            };
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstructorStanding"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    standings_progression_seasons__season__standings_progression_get: {
        parameters: {
            query?: {
                type?: "drivers" | "constructors";
                /** @description Solo los N primeros de la clasificación final */
                top?: number;
            };
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsProgression"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_races__race_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    race_results_races__race_id__results_get: {
        parameters: {
            query?: {
                session?: "race" | "sprint";
            };
            header?: never;
            path: {
                race_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    qualifying_races__race_id__qualifying_get: {
        parameters: {
            query?: {
                session?: "qualifying" | "sprint_qualifying";
            };
            header?: never;
            path: {
                race_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualifyingResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    laps_races__race_id__laps_get: {
        parameters: {
            query?: {
                /** @description Identificadores de piloto separados por comas */
                drivers?: string | null;
            };
            header?: never;
            path: {
                race_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lap"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stints_races__race_id__stints_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pit_stops_races__race_id__pitstops_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PitStop"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pit_lane_passes_races__race_id__pit_lane_passes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PitLanePass"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telemetry_races__race_id__telemetry_get: {
        parameters: {
            query: {
                /** @description De 1 a 4 identificadores de piloto, por comas */
                drivers: string;
            };
            header?: never;
            path: {
                race_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryLap"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drivers_drivers_get: {
        parameters: {
            query?: {
                /** @description Parte del nombre */
                search?: string | null;
                /** @description Solo pilotos de esta temporada */
                season?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_driver_drivers__driver_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_seasons_drivers__driver_id__seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverSeason"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_results_drivers__driver_id__results_get: {
        parameters: {
            query?: {
                season?: number | null;
            };
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverRaceResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    teammates_drivers__driver_id__teammates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeammateComparison"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_constructors_constructors_get: {
        parameters: {
            query?: {
                /** @description Parte del nombre */
                search?: string | null;
                /** @description Solo constructores de esta temporada */
                season?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstructorSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_constructor_constructors__constructor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                constructor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstructorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    constructor_seasons_constructors__constructor_id__seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                constructor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstructorSeason"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_records_records_drivers_get: {
        parameters: {
            query?: {
                metric?: "championships" | "wins" | "podiums" | "pole_positions" | "fastest_laps" | "race_starts" | "points" | "grand_slams";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    constructor_records_records_constructors_get: {
        parameters: {
            query?: {
                metric?: "championships" | "wins" | "podiums" | "pole_positions" | "fastest_laps" | "race_entries" | "one_two_finishes" | "points";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_rankings_rankings_drivers_get: {
        parameters: {
            query?: {
                /** @description Desde esta temporada */
                season_from?: number | null;
                /** @description Hasta esta temporada */
                season_to?: number | null;
                order_by?: "wins" | "championships" | "podiums" | "pole_positions" | "fastest_laps" | "points" | "entries";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverRanking"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    constructor_rankings_rankings_constructors_get: {
        parameters: {
            query?: {
                /** @description Desde esta temporada */
                season_from?: number | null;
                /** @description Hasta esta temporada */
                season_to?: number | null;
                order_by?: "wins" | "championships" | "podiums" | "pole_positions" | "fastest_laps" | "points" | "entries";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstructorRanking"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_circuits_circuits_get: {
        parameters: {
            query?: {
                /** @description Desde esta temporada */
                season_from?: number | null;
                /** @description Hasta esta temporada */
                season_to?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Circuit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    quality_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityCheck"][];
                };
            };
        };
    };
}
