{#- Tabla ancha de F1DB con una fila por piloto, sesión (`type`) y carrera. -#}
select
    race_id,
    type as session_type,
    position_display_order,
    position_number,
    position_text,
    driver_number,
    driver_id,
    constructor_id,
    engine_manufacturer_id,
    tyre_manufacturer_id,
    qualifying_time_millis,
    qualifying_q1_millis,
    qualifying_q2_millis,
    qualifying_q3_millis,
    qualifying_gap_millis,
    qualifying_laps,
    starting_grid_position_grid_penalty,
    starting_grid_position_grid_penalty_positions,
    race_shared_car::boolean as race_shared_car,
    race_laps,
    race_time_millis,
    race_time_penalty_millis,
    race_gap_millis,
    race_gap_laps,
    race_interval_millis,
    race_reason_retired,
    race_points,
    race_pole_position::boolean as race_pole_position,
    race_qualification_position_number,
    race_grid_position_number,
    race_grid_position_text,
    race_positions_gained,
    race_pit_stops,
    race_fastest_lap::boolean as race_fastest_lap,
    race_driver_of_the_day::boolean as race_driver_of_the_day,
    race_grand_slam::boolean as race_grand_slam,
    fastest_lap_lap,
    fastest_lap_time_millis,
    fastest_lap_gap_millis,
    pit_stop_stop,
    pit_stop_lap,
    pit_stop_time_millis
from {{ source('f1db', 'race_data') }}
